set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Set the prefix to Ctrl+a
set -g prefix C-a

# Unbind the old prefix
unbind C-b

# Send Ctr+a to applications by pressing it twice
bind C-a send-prefix

# Pane navigation with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# Dont confirm before killing pane
bind-key x kill-pane

# Split panes in a more mnemonic way
bind | split-window -h
bind - split-window -v

# fzf tmux sessions
bind-key -r f run-check "tmux neww tmux-sessionizer"

# open root shell
bind-key -r R run-shell "tmux-sessionizer ~/apps"


# make selected panes more obvious
set -g window-style 'fg=colour247,bg=colour235'
set -g window-active-style 'fg=default,bg=colour234'

# Pane border
set -g pane-border-bg default
set -g pane-border-fg colour238

# Active pane border
set -g pane-active-border-bg default
set -g pane-active-border-fg blue

